### ISSUE TITLE
MetaNetX v3.0

### ISSUE THREAD

**Issue by uludag** [mmundy42/cobrababel#1]
Test with `cobrababel.create_metanetx_universal_model()` function is failing with the current release of MetaNetX data files.

Changes in MetaNetX release files are highlighted on their downloads page: http://www.metanetx.org/mnxdoc/mnxref.html

Updating the check for the length of fields of _chem_prop.tsv_ file with 9 (in _metanetx.py_, line 68) makes the test pass in my environment. They added a new field (InChIKey) as the last/9th column. Format of the reaction equations was also updated but it looks current cobrababel regular expression for parsing is happy with the new format.
--mahmut

**Comment by mmundy42** [comment]
Thanks for letting me know. I'll update and push out a new release with the fix.

**Comment by mmundy42** [comment]
I've updated create_metanetx_universal_model() to support the latest MetaNetX release. The size of the chem_prop.tsv file became very large. I updated the function to only include metabolites in the universal model that are actually used in reactions defined in reac_prop.tsv. And that means the new fully compartmentalized reactions are supported too.
