### ISSUE TITLE
Tests fail with version 0.1.3 due to missing commma

### ISSUE THREAD

**Issue by smoretti** [mmundy42/cobrababel#3]
Hi

tests fails because a requirement for **cobra>=0.5.4six** is expected.

This is due to missing comma in setup.py
```
requirements = [
    'cobra>=0.5.4'
    'six',
```
that should be
```
requirements = [
    'cobra>=0.5.4',
    'six',
```

**Comment by mmundy42** [comment]
Thanks for reporting this one. Since I haven't loaded 0.1.3 into pypi yet, I'll get this fix in there.
